### ISSUE TITLE
Unable to change the width of the link preview.

### ISSUE THREAD

**Issue by starhopp3r** [bahrus/xtal-link-preview#1]
I tried to change the width of the link preview via CSS.

```css
xtal-link-preview{
    width: 100px;
}
```

But this is not working. How do I change the width?
